### ISSUE TITLE
Custom Callback URl

### ISSUE THREAD

**Issue by sour995** [paytm/Paytm_CSCart_Plugin#1] opened 2021-02-14 14:01 UTC
I am Using CS-Cart 4.11.5

1st this Issue: 
![Capture](https://user-images.githubusercontent.com/79048375/107878732-97a53c80-6efa-11eb-97ed-4ef31608e02c.JPG)

2nd Issue:
![Capture](https://user-images.githubusercontent.com/79048375/107878697-6cbae880-6efa-11eb-9f6b-e95537a293ed.JPG)

3rd Issue:
Even if I try a Successful Checkout, a error message in red comes on the top right corner, Says Server Communication error.

4th Issue:
When I cancel the payment from the payment page. and user is redirected back to site, the cart goes empty all of a sudden.

I think that if I can fix the custom callback URL all of this problems will be gone. Kindly let me know.

**Comment by abpaytm** [comment] 2021-06-07 13:33
Please try our latest plugin . The issue is now fixed

**Closed as completed by abpaytm** 2021-06-07 13:33 UTC
