### ISSUE TITLE
Issue while integrating Paytm plugin with CS-Cart 4.12.2

### ISSUE THREAD

**Issue by tabkad12** [paytm/Paytm_CSCart_Plugin#2] opened 2021-03-14 17:40 UTC
Hi,

I am using CS-Cart 4.12.2 on NGINX. I have installed Paytm plugin as per the instructions but unfortunately getting the following errors;

=======================================================================================
Error Message on Checkout Page as follows;
Oops, something went wrong (Internal Server Error). Please try again.

========================================================================================
Getting Error in the web logs as follows;

[error] 7935#7935: *352 FastCGI sent in stderr: "PHP message:  --> Smarty Compiler: Syntax error in template "/var/www/html/dev05.bigstorez.com/design/themes/responsive/templates/views/orders/components/payments/paytm.tpl"  on line 10 "<script type="application/javascript" crossorigin="anonymous" src="{{ srcUrl }}" onload="alert('Script loaded!'); loaded=true;"></script>"  - Unexpected "{ " <--" while reading response header from upstream, client: 11.11.11.6, server: www.mystore.com, request: "GET /index.php?dispatch=checkout.checkout&payment_id=17&full_render=true&result_ids=litecheckout_final_section%2Clitecheckout_step_payment%2Cshipping_rates_list%2Clitecheckout_terms%2Ccheckout*&is_ajax=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev05.bigstorez.com", referrer: "https://www.mystore.com/checkout/"

==========================================================================================

Any help or guidance in this regard will be highly appreciated.

Thanks in advance....

**Comment by abpaytm** [comment] 2021-06-07 13:32
Please try our latest plugin . The issue is now fixed

**Closed as completed by abpaytm** 2021-06-07 13:32 UTC
